// preact-vite/default-ts/after-storybook/src/stories/Button.jsx
import './button.css';

/**
 * Primary UI component for user interaction
 *
 * @param {object} props
 * @param {string} [props.primary=false] Default is `false`
 * @param {string} [props.backgroundColor]
 * @param {'small' | 'medium' | 'large'} [props.size='medium'] Default is `'medium'`
 * @param {string} props.label
 * @param {function} props.onClick
 */
export const Button = ({
  primary = false,
  backgroundColor = null,
  size = 'medium',
  label,
  ...props
}) => {
  const mode = primary ? 'storybook-button--primary' : 'storybook-button--secondary';
  return (
    <button
      type="button"
      className={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
      style={backgroundColor && { backgroundColor }}
      {...props}
    >
      {label}
    </button>
  );
};

// lit-vite/default-js/after-storybook/src/stories/Button.js
import { html } from 'lit';
import { styleMap } from 'lit/directives/style-map.js';

import './button.css';

/**
 * Primary UI component for user interaction
 */
export const Button = ({ primary, backgroundColor = null, size, label, onClick }) => {
  const mode = primary ? 'storybook-button--primary' : 'storybook-button--secondary';

  return html`
    <button
      type="button"
      class=${['storybook-button', `storybook-button--${size || 'medium'}`, mode].join(' ')}
      style=${styleMap({ backgroundColor })}
      @click=${onClick}
    >
      ${label}
    </button>
  `;
};
